import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import { syncPluginBuildOutputs } from "./sync-build-to-vault.mjs";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const nodeBuiltins = [...builtinModules, ...builtinModules.map((name) => `node:${name}`)];
const copyOutputsPlugin = {
	name: "copy-to-obsidian-vault",
	setup(build) {
		build.onEnd((result) => {
			if (result.errors.length > 0) {
				return;
			}

			syncPluginBuildOutputs({ reason: prod ? "build" : "dev" });
		});
	},
};

const pluginContext = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...nodeBuiltins],
	format: "cjs",
	platform: "node",
	target: "es2018",
	loader: {
		".css": "text",
	},
	jsx: "automatic",
	jsxImportSource: "preact",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: [copyOutputsPlugin],
});

const playerClientContext = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/network/player-client/app.tsx"],
	bundle: true,
	format: "iife",
	platform: "browser",
	target: "es2018",
	jsx: "automatic",
	jsxImportSource: "preact",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "player-client.js",
	minify: prod,
	plugins: [copyOutputsPlugin],
});

if (prod) {
	await Promise.all([pluginContext.rebuild(), playerClientContext.rebuild()]);
	process.exit(0);
} else {
	await Promise.all([pluginContext.watch(), playerClientContext.watch()]);
}
